filter:
    excluded_paths:
        - Resources/public
        - vendor
        - web

before_commands:
    - "composer install --prefer-dist --dev"

tools:
    php_mess_detector: true
    php_cs_fixer:
        config:
            level: all
    php_analyzer: ~
    php_code_sniffer:
        config:
            standard: PSR2
    sensiolabs_security_checker: true
    php_cpd: true
    php_loc: ~
    php_pdepend: ~
