language: php

php: [5.3.3, 5.3, 5.4, 5.5, hhvm]

matrix:
  allow_failures:
    - php: hhvm
    
cache:
  directories:
    - vendor

before_script:
  - composer install --prefer-source --dev
  - phantomjs --webdriver=4444 &
  - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock -s | grep "No known"'

script:
    - ./bin/phpspec run -fpretty
    - ./bin/behat --verbose
